apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "outreach-expenses.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "outreach-expenses.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.env.AWS_REGION | quote }}
