apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "outreach-expenses.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "outreach-expenses.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  AWS_REGION: {{ .Values.env.AWS_REGION | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
