apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "outreach-expenses.fullname" . }}-migration-{{ .Release.Revision }}
  labels:
    {{- include "outreach-expenses.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "outreach-expenses.fullname" . }}-migration
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command:
          - sh
          - -c
          - |
            echo "Waiting for database..."
            sleep 5
            yoyo apply -b --database $DATABASE_URL migrations
        envFrom:
        - configMapRef:
            name: {{ include "outreach-expenses.fullname" . }}
        - secretRef:
            name: {{ include "outreach-expenses.fullname" . }}
