apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outreach-expenses.fullname" . }}
  labels:
    {{- include "outreach-expenses.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.env.BOT_TOKEN | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.AWS_SECRET_ACCESS_KEY | quote }}
  S3_BUCKET: {{ .Values.env.S3_BUCKET | quote }}
