apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outreach-expenses.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "outreach-expenses.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.env.BOT_TOKEN | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.AWS_SECRET_ACCESS_KEY | quote }}
  S3_BUCKET: {{ .Values.env.S3_BUCKET | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "outreach-expenses.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
